export const dialogTitle = 'Create Post';
export const contentPlaceholder = "What's on your mind?";
export const addPhotoButtonText = 'Add Photo';
export const cancelButtonText = 'Cancel';
export const postButtonText = 'Post';
export const errorInvalidFileType = 'Please select an image file';
export const errorFileTooLarge = 'Image must be less than 5MB';
export const errorNoContent = 'Please add some content or an image';
export const errorCreatePost = 'Failed to create post';
